algoritmo "calculadora"
var
   //
   N1,N2,S,M,D,S=Real
   op=caractere

inicio
   Escreval ("Digite o primeiro número: ")
   Leia (N1)
   Escreval ("Escreva o segundo número: ")
   Leia (N2)
   Escreval ("Qual a operação?: (+) Adição, (-)Subtração, (\) Divisão, (*)Multiplicação")
   Leia (op)
   Escolha op
      Caso "+"
         S<-N1+N2
         Escreva ("A soma entre ".N1 "e" N2, é N1

         

   FimEscolha
fimalgoritmo